version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "store-customer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18dcx89lz8y8c"
s3_prefix = "store-customer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
